version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/evepvp


  frontend:
    build: ./solo-hunter-web
    ports:
      - "4173:4173"


